#!/bin/bash -x

host=ynaas.com
IFS=$' \t\n\r'

yn=(yes no)

read -r request _
while read -r header value; do
    [[ $header == Host: ]] && host=$value
    [[ $header == Content-Length: ]] && length=$value
    [[ $header ]] || break
done

case $request in
    GET)
        [[ $host == *.ynaas.com ]] && host=${host%.com}
        host=${host%.*}
        host=${host//\//}
        host=${host,,}
        ;;

    POST)
        IFS+=\& read -r -n "${length?}" subdomain yn
        yn=${yn#yn=}
        subdomain=${subdomain#subdomain=}
        if [[ $yn == yes || $yn == no ]]; then
            subdomain=${subdomain//\//}
            subdomain=${subdomain,,}

            ln "$yn" "$subdomain" &&
                exec printf 'HTTP/1.1 302 Found\r\nLocation: http://%s.ynaas.com\r\n\r\n' "$subdomain"
        fi
        ;;

    *)
        printf 'HTTP/1.1 200 OK\r\n\r\n'
        exit
        ;;
esac

if [[ -e $host ]]; then
    cat "$host"
else
    cat idk
fi
