#!/bin/bash -x

domain=127.0.0.1.nip.io
IFS=$' \t\n\r'

yn=(yes no)

read -r request _
while read -r header value; do
    [[ $header = Host: ]] && host=$value
    [[ $header = Content-Length: ]] && length=$value
    [[ $header ]] || break
done

[[ $host ]] ||
  exec printf 'HTTP/1.1 400 Bad Request\r\nConnection: close\r\n\r\n'

case $request in
    HEAD)
        exec printf 'HTTP/1.1 200 OK\r\nConnection: close\r\n\r\n'
        ;;

    GET)
        host=${host%:*} # strip port
        [[ $host = *.$domain ]] && host=${host%.$domain} || host=${host%%.*} # allow other names
        [[ $host = *.$domain ]] && host=${host%.$domain}
        host=${host//\/}
        host=${host,,}
        ;;

    POST)
        IFS+=\& read -r -n "${length?}" host yn
        yn=${yn#yn=}
        host=${host#subdomain=}
        if [[ $yn = yes || $yn = no ]]; then
            host=${host//\/}
            host=${host,,}

            ln "$yn" "$host" &&
            exec printf 'HTTP/1.1 302 Found\r\nConnection: close\r\nLocation: http://%s.%s\r\n\r\n' "$host" "$domain"
        fi
        ;;

    *)
        printf 'HTTP/1.1 501 Not Implemented\r\n\r\n'
        exit
        ;;
esac

[[ -e $host ]] && cat "$host" || cat idk
